[project]
name = "aai-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.4",
    "python-pptx>=1.0.2",
    "pyyaml>=6.0.2",
]
