version: "3"

tasks:
  help:
    desc: "Show help information for tasks"
    cmds:
      - task --list

  install:
    desc: "Install necessary packages"
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y ghostscript imagemagick latexmk
      - sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended
      - sudo apt-get install -y python3-pygments
  clean:
    desc: "Clean auxiliary files"
    cmds:
      - rm -rf *.aux *.log *.out *.toc *.bbl *.blg *.dvi *.fdb_latexmk *.fls *.synctex.gz *.xdv *.lof *.lot *.nav *.snm *.vrb *.gz *.toc

  status:
    desc: "Show generated files"
    silent: false
    cmds:
      - ls -l output || echo "No output directory or files yet."
