# Taskfile.yml
version: "3"

vars:
  TEMPLATE_PATH: assets/templates/template.pptx
  CONFIG_PATH: config/template.yml

tasks:
  default:
    desc: Run the complete workflow
    cmds:
      - task: setup
      - task: analyze:save
      - task: build
      - task: convert
    silent: true

  setup:
    desc: Create necessary directories
    cmds:
      - mkdir -p content
      - mkdir -p assets/templates
    status:
      - test -d content
      - test -d assets/templates

  install:deps:
    desc: Install required dependencies
    cmds:
      - |
        if ! command -v libreoffice >/dev/null 2>&1; then
          echo "LibreOffice not found. Installing LibreOffice..."
          sudo apt-get update
          sudo apt-get install -y libreoffice-common libreoffice-writer
        fi
    silent: true

  build:
    desc: Build PowerPoint presentations from YAML content
    deps: [setup]
    cmds:
      - python3 scripts/slide_creator.py
    sources:
      - content/*.yml
      - scripts/slide_creator.py
    generates:
      - "*.pptx"
    silent: true

  convert:
    desc: Convert PPTX to PDF using LibreOffice
    deps: [build]
    cmds:
      - ./scripts/pptx2pdf.sh
    sources:
      - "*.pptx"
    generates:
      - "*.pdf"

  analyze:
    desc: Analyze PowerPoint template
    cmds:
      - python3 scripts/analyze_template.py analyze {{.TEMPLATE_PATH}} {{.CONFIG_PATH}}

  validate:
      desc: Validate YAML content files
      cmds:
        - python3 scripts/validate_content.py

  clean:
    desc: Clean generated files
    cmds:
      - rm -f *.pptx *.pdf
    silent: true

  combine:
    desc: Run combine command
    cmds:
      - python3 combine.py
    silent: true

  update:task:
    desc: Update Task binary
    cmds:
      - echo "Updating Task binary..."
      - curl -sL https://taskfile.dev/install.sh | sh
      - rm -f "$HOME/.local/bin/task"
      - cp ./bin/task "$HOME/.local/bin/task"
      - mkdir -p "$HOME/bin"
      - rm -f "$HOME/bin/task"
      - ln -sf "$HOME/.local/bin/task" "$HOME/bin/task"
      - echo "Task binary updated."
