template:
  path: assets/templates/template.pptx
  dimensions:
    width: 13.33
    height: 7.5
layouts:
- name: 1 - Section Header
  layout_index: 1
  placeholder_count: 4
  shape_count: 4
  shapes:
  - shape_id: 2
    name: Title 1
    shape_type: placeholder
    placeholder:
      ph_type: TITLE (1)
      ph_idx: 0
      ph_sz: full
      ph_orient: horz
    text: Click to edit Master title style
  - shape_id: 3
    name: Date Placeholder 2
    shape_type: placeholder
    placeholder:
      ph_type: DATE (16)
      ph_idx: 10
      ph_sz: half
      ph_orient: horz
    text: 12/7/2024
  - shape_id: 4
    name: Footer Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: FOOTER (15)
      ph_idx: 11
      ph_sz: quarter
      ph_orient: horz
  - shape_id: 5
    name: Slide Number Placeholder 4
    shape_type: placeholder
    placeholder:
      ph_type: SLIDE_NUMBER (13)
      ph_idx: 12
      ph_sz: quarter
      ph_orient: horz
    text: ‹#›
- name: 2 - Title and Content
  layout_index: 2
  placeholder_count: 5
  shape_count: 5
  shapes:
  - shape_id: 2
    name: Title 1
    shape_type: placeholder
    placeholder:
      ph_type: TITLE (1)
      ph_idx: 0
      ph_sz: full
      ph_orient: horz
    text: Click to edit Master title style
  - shape_id: 4
    name: Text Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: BODY (2)
      ph_idx: 10
      ph_sz: quarter
      ph_orient: horz
    text: 'Click to edit Master text styles

      Second level

      Third level

      Fourth level

      Fifth level'
  - shape_id: 5
    name: Date Placeholder 2
    shape_type: placeholder
    placeholder:
      ph_type: DATE (16)
      ph_idx: 11
      ph_sz: half
      ph_orient: horz
    text: 12/7/2024
  - shape_id: 6
    name: Footer Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: FOOTER (15)
      ph_idx: 12
      ph_sz: quarter
      ph_orient: horz
  - shape_id: 7
    name: Slide Number Placeholder 4
    shape_type: placeholder
    placeholder:
      ph_type: SLIDE_NUMBER (13)
      ph_idx: 13
      ph_sz: quarter
      ph_orient: horz
    text: ‹#›
- name: 3 - Comparison
  layout_index: 3
  placeholder_count: 8
  shape_count: 8
  shapes:
  - shape_id: 13
    name: Text Placeholder 2
    shape_type: placeholder
    placeholder:
      ph_type: BODY (2)
      ph_idx: 1
      ph_sz: full
      ph_orient: horz
    text: Click to edit Master text styles
  - shape_id: 14
    name: Content Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: OBJECT (7)
      ph_idx: 2
      ph_sz: half
      ph_orient: horz
    text: 'Click to edit Master text styles

      Second level

      Third level

      Fourth level

      Fifth level'
  - shape_id: 17
    name: Title 1
    shape_type: placeholder
    placeholder:
      ph_type: TITLE (1)
      ph_idx: 0
      ph_sz: full
      ph_orient: horz
    text: Click to edit Master title style
  - shape_id: 18
    name: Text Placeholder 2
    shape_type: placeholder
    placeholder:
      ph_type: BODY (2)
      ph_idx: 13
      ph_sz: full
      ph_orient: horz
    text: Click to edit Master text styles
  - shape_id: 19
    name: Content Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: OBJECT (7)
      ph_idx: 14
      ph_sz: half
      ph_orient: horz
    text: 'Click to edit Master text styles

      Second level

      Third level

      Fourth level

      Fifth level'
  - shape_id: 7
    name: Date Placeholder 2
    shape_type: placeholder
    placeholder:
      ph_type: DATE (16)
      ph_idx: 15
      ph_sz: half
      ph_orient: horz
    text: 12/7/2024
  - shape_id: 8
    name: Footer Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: FOOTER (15)
      ph_idx: 16
      ph_sz: quarter
      ph_orient: horz
  - shape_id: 9
    name: Slide Number Placeholder 4
    shape_type: placeholder
    placeholder:
      ph_type: SLIDE_NUMBER (13)
      ph_idx: 17
      ph_sz: quarter
      ph_orient: horz
    text: ‹#›
- name: 4- Blank
  layout_index: 4
  placeholder_count: 3
  shape_count: 3
  shapes:
  - shape_id: 2
    name: Date Placeholder 2
    shape_type: placeholder
    placeholder:
      ph_type: DATE (16)
      ph_idx: 10
      ph_sz: half
      ph_orient: horz
    text: 12/7/2024
  - shape_id: 3
    name: Footer Placeholder 3
    shape_type: placeholder
    placeholder:
      ph_type: FOOTER (15)
      ph_idx: 11
      ph_sz: quarter
      ph_orient: horz
  - shape_id: 4
    name: Slide Number Placeholder 4
    shape_type: placeholder
    placeholder:
      ph_type: SLIDE_NUMBER (13)
      ph_idx: 12
      ph_sz: quarter
      ph_orient: horz
    text: ‹#›
summary:
  total_layouts: 4
  total_placeholders: 20
  total_shapes: 20
