# ci_cd_workflow.yml
#
# This workflow:
# - Runs on pushes and pull requests to main
# - Sets up Python environment
# - Installs dependencies
# - Runs tests, model validation, and bias checks
# - Performs a security scan
# - If all checks pass, deploys to a staging environment for validation

name: ML Model Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      # Part 1: Set up environment
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Part 2: Install dependencies, run tests, and bias checks
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Run tests and validation
        run: |
          pytest tests/
          python scripts/validate_model.py
          python scripts/check_bias.py

      # Part 3: Security scan and deploy to staging
      - name: Security scan
        uses: anchore/scan-action@v3
        with:
          image: "model-service:${{ github.sha }}"
          fail-build: true
          severity-cutoff: high

      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/staging/
          python scripts/validate_deployment.py --environment staging
