template:
  path: assets/templates/template.pptx
  dimensions:
    width: 13.33
    height: 7.5
layouts:
- name: 1 - Section Header
  placeholders:
  - index: 0
    type: TITLE (TITLE (1))
    type_id: TITLE
    name: Title 1
  - index: 10
    type: DATE (DATE (16))
    type_id: DATE
    name: Date Placeholder 2
  - index: 11
    type: FOOTER (FOOTER (15))
    type_id: FOOTER
    name: Footer Placeholder 3
  - index: 12
    type: SLIDE_NUMBER (SLIDE_NUMBER (13))
    type_id: SLIDE_NUMBER
    name: Slide Number Placeholder 4
- name: 2 - Title and Content
  placeholders:
  - index: 0
    type: TITLE (TITLE (1))
    type_id: TITLE
    name: Title 1
  - index: 10
    type: BODY (BODY (2))
    type_id: BODY
    name: Text Placeholder 3
  - index: 11
    type: DATE (DATE (16))
    type_id: DATE
    name: Date Placeholder 2
  - index: 12
    type: FOOTER (FOOTER (15))
    type_id: FOOTER
    name: Footer Placeholder 3
  - index: 13
    type: SLIDE_NUMBER (SLIDE_NUMBER (13))
    type_id: SLIDE_NUMBER
    name: Slide Number Placeholder 4
- name: 3 - Comparison
  placeholders:
  - index: 1
    type: BODY (BODY (2))
    type_id: BODY
    name: Text Placeholder 2
  - index: 2
    type: OBJECT (OBJECT (7))
    type_id: OBJECT
    name: Content Placeholder 3
  - index: 0
    type: TITLE (TITLE (1))
    type_id: TITLE
    name: Title 1
  - index: 13
    type: BODY (BODY (2))
    type_id: BODY
    name: Text Placeholder 2
  - index: 14
    type: OBJECT (OBJECT (7))
    type_id: OBJECT
    name: Content Placeholder 3
  - index: 15
    type: DATE (DATE (16))
    type_id: DATE
    name: Date Placeholder 2
  - index: 16
    type: FOOTER (FOOTER (15))
    type_id: FOOTER
    name: Footer Placeholder 3
  - index: 17
    type: SLIDE_NUMBER (SLIDE_NUMBER (13))
    type_id: SLIDE_NUMBER
    name: Slide Number Placeholder 4
- name: 4- Blank
  placeholders:
  - index: 10
    type: DATE (DATE (16))
    type_id: DATE
    name: Date Placeholder 2
  - index: 11
    type: FOOTER (FOOTER (15))
    type_id: FOOTER
    name: Footer Placeholder 3
  - index: 12
    type: SLIDE_NUMBER (SLIDE_NUMBER (13))
    type_id: SLIDE_NUMBER
    name: Slide Number Placeholder 4
